[package]
name = "hello"
version = "0.1.0"
authors = ["Matthew Harwood <harwood@uber.com"]
publish = false
description = "this is a test"
license = "MIT"
keywords = ["demo"]
repository = ""
documentation = ""
edition = "2018"
